### ISSUE TITLE
Audio sharing between macOS Monterey and Android not supported

### ISSUE THREAD

**Issue by JeremiahDuane** [koush/vysor.io#1035]
Sharing audio between these devices is impossible. Audio toggle elicits no actions.

**Comment by renanborgez** [comment]
Was this issue solved?

**Comment by koush** [comment]
this is a duplicate issue.

**Comment by koush** [comment]
follow the instructions? not hard.

**Comment by koush** [comment]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/73924/158441968-4f5a981c-c35e-452c-9b78-180bfda5eec5.png">

**Comment by huttarl** [comment]
Unfortunately, in cases where the bug report instructions were followed (e.g. #1000, #936), the issue was closed as "duplicate" with no indication of which issue it was considered to be a duplicate of. So it's very difficult to follow up and find out whether the developer thinks the issue is solved or not.
