### ISSUE TITLE
Enterprise Account(Android) does not work over VPN: Connection to Vysor Share Server failed. undefined 

### ISSUE THREAD

**Issue by itissid** [koush/vysor.io#1078]
To be sure I can access my device remotely outside of a vpn. Whenever vysor host or client is connected to VPN I cannot access it.

Could we somehow exclu

I have an enterprise account registered with itissid@gmail.com.

**Comment by RenatoCapelo** [comment]
Is the problem occurring while connecting via USB and wirelessly or only wirelessly?

**Comment by itissid** [comment]
I did not try wireless I only care about USB connected Android devices

**Comment by RenatoCapelo** [comment]
hm, that's weird 🤔I have an active VPN connection on both my devices (Android and IOS) and I only had problems while trying to connect to them wirelessly... Your VPN client might be blocking USB debugging in general... An easy way to see if this is the problem is checking on a tool like Android Studio if your phone is showing up on the device list! if it's not, you'll have to contact your VPN provider and tell them about the issue with your client app.
If it is showing up, then I don't know what else might be the problem :/

**Comment by koush** [comment]
I'd ask your IT team.
