### ISSUE TITLE
Vysor is still looking for app_process32 in a 64-bit environment, which the 32-bit runtime doesn't exist.

### ISSUE THREAD

**Issue by seventhmoon** [koush/vysor.io#1116]
Vysor is trying to execute `app_process32` when the connection starts.
However, 32-bit runtime does not exist in a **64-bit ONLY** environment.
Vysor should use `app_process` which link to `app_process64` in 64-bit only env.

**Desktop (please complete the following information):**
 - OS: MacOS, Windows, Linux, Web Interface
 - App Version: 3.1.4, 4.2.2

**Comment by koush** [comment]
I believe I got this issue reported from the google app compat team as well. are you on that team? is there a developer image I can test for pixel 5 or something?

**Comment by koush** [comment]
Here's the code I currently have to do platform detection:

```
  const test = await Adb.shell(Object.assign({}, options, {
    command: 'ls -l /system/bin/app_process*',
  }));

  let appProcess = '/system/bin/app_process';
  if (test && test.indexOf('app_process32') !== -1) {
    // found what looks to be a 32 bit app_process, so lets force it.
    appProcess += '32';
  }
```

```

**Comment by seventhmoon** [comment]
```
  if (test && test.indexOf('app_process32') !== -1) {
    // found what looks to be a 32 bit app_process, so lets force it.
    appProcess += '32';
  }
  ```

Sorry, I should make it clear. 
In a 64-bit only device, 32-bit runtime doesn't exist.
The file `app_process32` may or may not exist. But since 32-bit runtime is missing, the `app_process32` could not be executed.

Should it always run the `app_process` as it will link to the correct `app_process32` or `app_process64` on different device?

**Comment by enh-google** [comment]
> I believe I got this issue reported from the google app compat team as well. are you on that team? is there a developer image I can test for pixel 5 or something?

if you're able to build AOSP, there is a redfin configuration available:

https://android-review.googlesource.com/c/device/google/redfin/+/2153433

if you can't, you could always share an apk with us and we can test for you.

> This should work, but it apparently does not?

as you can tell from that change, the configuration is actually "64-bit only, but with 32-bit binaries still on disk", which is why your code is confused. if you're wondering "why on earth would anyone configure a device like that?!" mainly so that they can have a single system image that they use across both their "traditional" 64/32 devices and their 64-only devices during the transition period [https://www.arm.com/blogs/blueprint/64-bit].

(and this is why testing with one of the 64-only emulator images, wouldn't help --- that _doesn't_ have the 32-bit stuff on disk, so wouldn't tickle this bug.)

tbh, i'm not clear why you even have this code... why do you want to prefer 32-bit over 64-bit on a device that's capable of 64-bit? fwiw, the correct way to get the supported ABIs is to look at the `ro.product.cpu.abi*` properties. `ro.product.cpu.abi` tells you the "best" ABI, `ro.product.cpu.abilist` tells you all the ABIs, and `ro.product.cpu.abilist32` and `ro.product.cpu.abilist64` tell you all the 32-bit and 64-bit ABIs respectively.

the advice to "just run `app_process`" is equivalent to checking `ro.product.cpu.abi` and running `app_process32` or `app_process64` based on that. if you actually _need_ to run the 32-bit version even on a 64-bit-capable device (as your current code appears to do), that's likely to be a much harder fix because that's just not going to be possible on 64-only devices.

@cferris1000 too, since he's been doing the most work on our side...

**Comment by koush** [comment]
> tbh, i'm not clear why you even have this code...

Vysor's been around for around 8 years worth of android versions. There's probably good reasons related to legacy android versions that I can't recall at the moment. I'm fairly sure I tried the obvious "just run app_process" approach, and quickly discovered a reason this code needs to exist. I'll revisit it.

**Comment by cferris1000** [comment]
Did the app installed use to have native code? If so, that might explain the preference if you didn't have a 64 bit native part.

As of now, it looks like the app is pure java, so it, theoretically, shouldn't matter if it runs using app_process32 or app_process64.

**Comment by koush** [comment]
> Did the app installed use to have native code? If so, that might explain the preference if you didn't have a 64 bit native part.
> 
> As of now, it looks like the app is pure java, so it, theoretically, shouldn't matter if it runs using app_process32 or app_process64.

I think at one point it used renderscript for some androids to do a pixel format conversion, but I think that has been since stripped out.

I've published a new build that uses app_process64 explicitly if it exists. Reversed the logic.

**Comment by koush** [comment]
4.2.7

**Comment by koush** [comment]
> I've published a new build that uses app_process64 explicitly if it exists. Reversed the logic.

I'm a bit wary of pointing it to app_process until I fully understand the scope of this change with regard to arch. At first glance, I agree, since there's no more native dependencies, I think in theory it should be possible to do that.

**Comment by enh-google** [comment]
> I think at one point it used renderscript for some androids to do a pixel format conversion, but I think that has been since stripped out.

ah, that would make sense... i do remember there being some 64-bit issues with renderscript. (stuff like https://stackoverflow.com/questions/56356532/renderscript-and-playstore-64-bit-requirement for example.)

> I've published a new build that uses app_process64 explicitly if it exists. Reversed the logic.

that solves _our_ problem (thanks!) but could _theoretically_ cause issues for an OEM trying to ship 32-only devices from "one true system image"? i'd guess we'll never see such a device in practice because if they're shipping a 32-only device that's probably to save money, so why wouldn't they save flash space by removing the unused 64-bit code?

heh... i was going to finish with "...so although this probably isn't a pressing problem, i'd still suggest trying to move to just plain `app_process`, and if you ever have a device that causes you trouble with that, let me know and we'll add the CTS test to stop them being naughty!", but you just ninja'ed me and said you're going to look into it later anyway :-)

> 4.2.7

is there somewhere we can point your customers to where they can download that? github seems to only go up to 4.2.3...

thanks again!

**Comment by seventhmoon** [comment]
The web interface app.vysor.io is showing Version: 4.2.7 (runtime 4.2.7) and solved the issue.

**Comment by koush** [comment]
> is there somewhere we can point your customers to where they can download that? github seems to only go up to 4.2.3...

it's already live in the beta channel for the desktop app and and pwa, and  I'll put it in the stable channel when I'm confident it's not a risky change.

**Comment by enh-google** [comment]
awesome, thanks! (both to koush who fixed it in the first place and seventhmoon who already managed to test it and confirm it works!)

like i say, hopefully your plain `app_process` issues were just historical renderscript-induced accidents, but let us know if you hit any trouble with that...

**Comment by koush** [comment]
@seventhmoon released this fix last week in the stable Chanel for the pixel 7, thanks 😅
