### ISSUE TITLE
No Umlaut keys on a german windows 10

### ISSUE THREAD

**Issue by Iqon** [koush/vysor.io#117]
It is not possible to enter the german umlaut keys (like ä,ö or ü) on windows 10.

**Comment by Iqon** [comment]
It is not possible to enter the german umlaut keys (like ä,ö or ü) on windows 10.

**Comment by VitorLuizC** [comment]
I think the same happens to accents in portuguese keys on windows 10.
#116

**Comment by dozzer** [comment]
Also this issue reproduce with cyrillic chars (Ukranian)

**Comment by vanderLo** [comment]
I can confirm the problem with the missing (German) special characters.

**Comment by SebMik** [comment]
This seems to be caused by the mothod KeyCharacterMap.getEvents(char[]) returning null, resulting in a NullPointerException (around line 252). The documentation suggests not using that medhod, and instead constructing a KeyEvent with action code ACTION_MULTIPLE. [link](http://developer.android.com/reference/android/view/KeyCharacterMap.html#getEvents(char[]))

**Comment by koush** [comment]
https://github.com/koush/vysor.io/issues/4
