### ISSUE TITLE
Failed to execute 'claimInterface' on 'USBDevice'

### ISSUE THREAD

**Issue by trippme** [koush/vysor.io#1223]
Details: 
Windows 11: Version	10.0.22621 Build 22621
Pixel 7Pro - Android 13 build # TQ2A.230305.008.C1
Installed ADB Drivers
Install Vysor on PC and Phone (phone has previously run Vysor no problem this is a new PC)
Rebooted both devices
Ensured PC can interact with phone data wise (can copy photos to/from phone to PC using same setup)

Full error: Error connecting to Android Device NetworkError: Failed to execute 'claimInterface' on 'USBDevice'. Unable to claim interface

**Comment by koush** [comment]
seems like you're using the PWA, use the native app on windows. If it the status area indicates you are using webusb, you're using the PWA. it needs to say "adb server".

**Comment by trippme** [comment]
That solved it.

**Comment by AkenoSan06** [comment]
Same İssue happened to me. Vysor app has worked 3 hours ago but now app and browser says Error connecting to Android Device NetworkError: Failed to execute 'claimInterface' on 'USBDevice'. Unable to claim interface

**Comment by cidfarzan** [comment]
same problem, updated to android 13 beta 3 last night, both pc windows 10 and 11 computers would not connect, identifies device, tries to connect, then error, rebooted phone, disabled usb debugging, uninstalled and reinstalled vysor, need help.

OS: windows 10 / Windows 11
Device : Pixel 7 Pro
Android 14 Beta 3
Vysor Version 5.0.16 runtime 5.0.7
Vysor Bug Remport Link  [https://gist.github.com/VysorLogs/75b8ca826fc8c5793fce13172f0a9bb8]
((https://gist.github.com/VysorLogs/75b8ca826fc8c5793fce13172f0a9bb8))

![image](https://github.com/koush/vysor.io/assets/136014633/8666925c-5dd7-42cb-8c42-dcbb290e59b0)

**Comment by Mykola-Veryha** [comment]
Same issue on Ubuntu 23

**Comment by oneinterpreting** [comment]
I experienced the same error. Uninstalling the native Vysor app for Windows resolved it for me. I was then able to use the PWA version in the browser without issues (Chrome or Edge). But I decided to follow the advice of Koush and reinstalled Vysor for Windows since it has more functionality. Same error occurs now when trying to use the PWA in the browser so at least it's reproducible. I'll reserve the PWA browser version for when I'm on a public computer or someone else's machine becuase it works beautifully in instances where you can't install a native app.

OS: Windows 11 Pro, build 22621.2283
Device: Samsung Galaxy Tab A7 Lite running Android 13, One UI Core version 5.1
Google Chrome: version 116.0.5845.188 (Official Build) (64-bit)
Microsoft Edge: version 117.0.2045.31 (Official build) (64-bit)
Vysor-win-5.0.7.exe
