### ISSUE TITLE
Spinning "loading" icon never goes away when trying to connect

### ISSUE THREAD

**Issue by Wargazm** [koush/vysor.io#13]
Moto X 2013, VZW Dev edition.  

Vysor sees my phone and begins to attempt connection, but all I see is this:

https://i.imgur.com/II98Ylj.png

One thing to note, I am at work, where our network is crippled for security purposes.  Since it's over USB I don't see why that should matter, but I figured I'd mention it.  In any case, there might be some other services that Vysor is dependent on that have been crippled on my work PC.  

If this is expected to work, I'd be happy to post any debug logs, etc.

**Comment by sympathy4all** [comment]
As reported in the G+ post here is the log for the same problem :  an endless spinning circle

protocol version: sh: linker:: not found
sh: WARNING:: not found
sh: /data/app/com.koushikdutta.vysor-2.apk: can't execute: Permission denied
uglify.js:1 installing apk
uglify.js:1 protocol version: sh: linker:: not found
sh: WARNING:: not found
sh: /data/app/com.koushikdutta.vysor-1.apk: can't execute: Permission denied
uglify.js:1 wtf apk install failed? WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
    pkg: /data/local/tmp/vysor1440520211205.apk
Success

in this folder /data/app/  i've got com.koushikdutta.vysor-1.apk . I think the premission is Okay rw-r-r, after uninstalling it, it has been replaced by com.koushikdutta.vysor-2.apk

and in the temp folder a lot of apks.

**Comment by koush** [comment]
from a command prompt on your computer, try running the following and let me know if it works:

```
adb shell am
```

I am assuming you have an understanding of adb.

**Comment by koush** [comment]
@sympathy4all let me know if you can do a chrome remote desktop session and i can debug this on your computer myself. this is a really strange bug.

**Comment by Wargazm** [comment]
Not sure what "working" looks like.  This is the output  `adb shel am`:

    WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
    WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
    usage: am [subcommand] [options]
    usage: am start [-D] [-W] [-P <FILE>] [--start-profiler <FILE>]
                   [--R COUNT] [-S] [--opengl-trace]
                   [--user <USER_ID> | current] <INTENT>
           am startservice [--user <USER_ID> | current] <INTENT>
           am stopservice [--user <USER_ID> | current] <INTENT>
           am force-stop [--user <USER_ID> | all | current] <PACKAGE>
           am kill [--user <USER_ID> | all | current] <PACKAGE>
           am kill-all
           am broadcast [--user <USER_ID> | all | current] <INTENT>
           am instrument [-r] [-e <NAME> <VALUE>] [-p <FILE>] [-w]
                   [--user <USER_ID> | current]
                   [--no-window-animation] <COMPONENT>
           am profile start [--user <USER_ID> current] <PROCESS> <FILE>
           am profile stop [--user <USER_ID> current] [<PROCESS>]
           am dumpheap [--user <USER_ID> current] [-n] <PROCESS> <FILE>
           am set-debug-app [-w] [--persistent] <PACKAGE>
           am clear-debug-app
           am monitor [--gdb <port>]
           am hang [--allow-restart]
           am restart
           am idle-maintenance
           am screen-compat [on|off] <PACKAGE>
           am to-uri [INTENT]
           am to-intent-uri [INTENT]
           am switch-user <USER_ID>
           am stop-user <USER_ID>
           am stack create <TASK_ID> <RELATIVE_STACK_BOX_ID> <POSITION> <WEIGHT>
           am stack movetask <TASK_ID> <STACK_ID> [true|false]
           am stack resize <STACK_ID> <WEIGHT>
           am stack boxes
           am stack box <STACK_BOX_ID>

    am start: start an Activity.  Options are:
        -D: enable debugging
        -W: wait for launch to complete
        --start-profiler <FILE>: start profiler and send results to <FILE>
        -P <FILE>: like above, but profiling stops when app goes idle
        -R: repeat the activity launch <COUNT> times.  Prior to each repeat,
            the top activity will be finished.
        -S: force stop the target app before starting the activity
        --opengl-trace: enable tracing of OpenGL functions
        --user <USER_ID> | current: Specify which user to run as; if not
            specified then run as the current user.

    am startservice: start a Service.  Options are:
        --user <USER_ID> | current: Specify which user to run as; if not
            specified then run as the current user.

    am stopservice: stop a Service.  Options are:
        --user <USER_ID> | current: Specify which user to run as; if not
            specified then run as the current user.

    am force-stop: force stop everything associated with <PACKAGE>.
        --user <USER_ID> | all | current: Specify user to force stop;
            all users if not specified.

    am kill: Kill all processes associated with <PACKAGE>.  Only kills.
      processes that are safe to kill -- that is, will not impact the user
      experience.
        --user <USER_ID> | all | current: Specify user whose processes to kill;
            all users if not specified.

    am kill-all: Kill all background processes.

    am broadcast: send a broadcast Intent.  Options are:
        --user <USER_ID> | all | current: Specify which user to send to; if not
            specified then send to all users.
        --receiver-permission <PERMISSION>: Require receiver to hold permission.

    am instrument: start an Instrumentation.  Typically this target <COMPONENT>
      is the form <TEST_PACKAGE>/<RUNNER_CLASS>.  Options are:
        -r: print raw results (otherwise decode REPORT_KEY_STREAMRESULT).  Use with
            [-e perf true] to generate raw output for performance measurements.
        -e <NAME> <VALUE>: set argument <NAME> to <VALUE>.  For test runners a
            common form is [-e <testrunner_flag> <value>[,<value>...]].
        -p <FILE>: write profiling data to <FILE>
        -w: wait for instrumentation to finish before returning.  Required for
            test runners.
        --user <USER_ID> | current: Specify user instrumentation runs in;
            current user if not specified.
        --no-window-animation: turn off window animations while running.

    am profile: start and stop profiler on a process.  The given <PROCESS> argument
      may be either a process name or pid.  Options are:
        --user <USER_ID> | current: When supplying a process name,
            specify user of process to profile; uses current user if not specified.

    am dumpheap: dump the heap of a process.  The given <PROCESS> argument may
      be either a process name or pid.  Options are:
        -n: dump native heap instead of managed heap
        --user <USER_ID> | current: When supplying a process name,
            specify user of process to dump; uses current user if not specified.

    am set-debug-app: set application <PACKAGE> to debug.  Options are:
        -w: wait for debugger when application starts
        --persistent: retain this value

    am clear-debug-app: clear the previously set-debug-app.

    am bug-report: request bug report generation; will launch UI
        when done to select where it should be delivered.

    am monitor: start monitoring for crashes or ANRs.
        --gdb: start gdbserv on the given port at crash/ANR

    am hang: hang the system.
        --allow-restart: allow watchdog to perform normal system restart

    am restart: restart the user-space system.

    am idle-maintenance: perform idle maintenance now.

    am screen-compat: control screen compatibility mode of <PACKAGE>.

    am to-uri: print the given Intent specification as a URI.

    am to-intent-uri: print the given Intent specification as an intent: URI.

    am switch-user: switch to put USER_ID in the foreground, starting
      execution of that user if it is currently stopped.

    am stop-user: stop execution of USER_ID, not allowing it to run any
      code until a later explicit switch to it.

    am stack create: create a new stack relative to an existing one.
       <TASK_ID>: the task to populate the new stack with. Must exist.
       <RELATIVE_STACK_BOX_ID>: existing stack box's id.
       <POSITION>: 0: before <RELATIVE_STACK_BOX_ID>, per RTL/LTR configuration,
                   1: after <RELATIVE_STACK_BOX_ID>, per RTL/LTR configuration,
                   2: to left of <RELATIVE_STACK_BOX_ID>,
                   3: to right of <RELATIVE_STACK_BOX_ID>,               4: above <RELATIVE_STACK_BOX_ID>, 5: below <RELATIVE_STACK_BOX_ID>
       <WEIGHT>: float between 0.2 and 0.8 inclusive.

    am stack movetask: move <TASK_ID> from its current stack to the top (true) or   bottom (false) of <STACK_ID>.

    am stack resize: change <STACK_ID> relative size to new <WEIGHT>.

    am stack boxes: list the hierarchy of stack boxes and their contents.

    am stack box: list the hierarchy of stack boxes rooted at <STACK_BOX_ID>.

    <INTENT> specifications include these flags and arguments:
        [-a <ACTION>] [-d <DATA_URI>] [-t <MIME_TYPE>]
        [-c <CATEGORY> [-c <CATEGORY>] ...]
        [-e|--es <EXTRA_KEY> <EXTRA_STRING_VALUE> ...]
        [--esn <EXTRA_KEY> ...]
        [--ez <EXTRA_KEY> <EXTRA_BOOLEAN_VALUE> ...]
        [--ei <EXTRA_KEY> <EXTRA_INT_VALUE> ...]
        [--el <EXTRA_KEY> <EXTRA_LONG_VALUE> ...]
        [--ef <EXTRA_KEY> <EXTRA_FLOAT_VALUE> ...]
        [--eu <EXTRA_KEY> <EXTRA_URI_VALUE> ...]
        [--ecn <EXTRA_KEY> <EXTRA_COMPONENT_NAME_VALUE>]
        [--eia <EXTRA_KEY> <EXTRA_INT_VALUE>[,<EXTRA_INT_VALUE...]]
        [--ela <EXTRA_KEY> <EXTRA_LONG_VALUE>[,<EXTRA_LONG_VALUE...]]
        [--efa <EXTRA_KEY> <EXTRA_FLOAT_VALUE>[,<EXTRA_FLOAT_VALUE...]]
        [-n <COMPONENT>] [-f <FLAGS>]
        [--grant-read-uri-permission] [--grant-write-uri-permission]
        [--debug-log-resolution] [--exclude-stopped-packages]
        [--include-stopped-packages]
        [--activity-brought-to-front] [--activity-clear-top]
        [--activity-clear-when-task-reset] [--activity-exclude-from-recents]
        [--activity-launched-from-history] [--activity-multiple-task]
        [--activity-no-animation] [--activity-no-history]
        [--activity-no-user-action] [--activity-previous-is-top]
        [--activity-reorder-to-front] [--activity-reset-task-if-needed]
        [--activity-single-top] [--activity-clear-task]
        [--activity-task-on-home]
        [--receiver-registered-only] [--receiver-replace-pending]
        [--selector]
        [<URI> | <PACKAGE> | <COMPONENT>]

**Comment by inbarori** [comment]
i got the same issue - spinning loading.
the keyboard and mouse are working.

i saw i am missing screenrecord from my build - so i downloaded the one from https://github.com/madisp/mimic/tree/master/bin

which seems to work - but still no image.

and if this works - it would be a great chrome app!

-ori

**Comment by koush** [comment]
```
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.
```
You're rooted I'm guessing. I just fixed this problem in 1038. Rolling out shortly.

**Comment by Wargazm** [comment]
yes, I am rooted.  should have mentioned that earlier!  I'll await the new build.

**Comment by DennisLfromGA** [comment]
I am *not* rooted, is it necessary for full functionality?

**Comment by koush** [comment]
@DennisLfromGA no, root is not necessary

**Comment by DennisLfromGA** [comment]
Okay then, thanx.
I guess I'm at the same point as @Wargazm - https://github.com/koush/vysor.io/issues/13#issuecomment-134707552

**Comment by inbarori** [comment]
i do see weird stuff on logcat:

08-25 15:44:25.259 E/memtrack( 1646): Couldn't load memtrack module (No such file or directory)

08-25 15:44:25.259 E/android.os.Debug( 1646): failed to load memtrack module: -2
...

08-25 15:44:26.989 E/NIO     ( 1682): wtf

08-25 15:44:26.989 E/NIO     ( 1682): java.net.BindException: bind failed: EADDRINUSE (Address already in use)

08-25 15:44:26.989 E/NIO     ( 1682): 	at libcore.io.IoBridge.bind(IoBridge.java:89)

08-25 15:44:26.989 E/NIO     ( 1682): 	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:150)

08-25 15:44:26.989 E/NIO     ( 1682): 	at java.net.ServerSocket.bind(ServerSocket.java:319)

08-25 15:44:26.989 E/NIO     ( 1682): 	at java.nio.ServerSocketChannelImpl$ServerSocketAdapter.bind(ServerSocketChannelImpl.java:124)

08-25 15:44:26.989 E/NIO     ( 1682): 	at java.net.ServerSocket.bind(ServerSocket.java:282)

08-25 15:44:26.989 E/NIO     ( 1682): 	at java.nio.ServerSocketChannelImpl$ServerSocketAdapter.bind(ServerSocketChannelImpl.java:167)

08-25 15:44:26.989 E/NIO     ( 1682): 	at com.koushikdutta.async.AsyncServer$5.run(AsyncServer.java:299)

08-25 15:44:26.989 E/NIO     ( 1682): 	at com.koushikdutta.async.AsyncServer$3.run(AsyncServer.java:194)

08-25 15:44:26.989 E/NIO     ( 1682): 	at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:709)

08-25 15:44:26.989 E/NIO     ( 1682): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:726)

08-25 15:44:26.989 E/NIO     ( 1682): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)

08-25 15:44:26.989 E/NIO     ( 1682): 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)

08-25 15:44:26.989 E/NIO     ( 1682): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)

08-25 15:44:26.989 E/NIO     ( 1682): Caused by: libcore.io.ErrnoException: bind failed: EADDRINUSE (Address already in use)

08-25 15:44:26.989 E/NIO     ( 1682): 	at libcore.io.Posix.bind(Native Method)

08-25 15:44:26.989 E/NIO     ( 1682): 	at libcore.io.ForwardingOs.bind(ForwardingOs.java:40)

08-25 15:44:26.989 E/NIO     ( 1682): 	at libcore.io.IoBridge.bind(IoBridge.java:87)

....

08-25 15:44:26.989 W/dalvikvm( 1682): threadid=1: thread exiting with uncaught exception (group=0x4164dba8)

08-25 15:44:26.989 E/JavaBinder( 1682): Unknown binder error code. 0xfffffff7

08-25 15:44:26.989 E/ServiceManager( 1682): error in getService

08-25 15:44:26.989 E/ServiceManager( 1682): android.os.RemoteException: Unknown binder error code. 0xfffffff7

08-25 15:44:26.989 E/ServiceManager( 1682): 	at android.os.BinderProxy.transact(Native Method)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at android.os.ServiceManager.getService(ServiceManager.java:55)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2042)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at android.app.ActivityManagerNative$1.create(ActivityManagerNative.java:2040)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at android.util.Singleton.get(Singleton.java:34)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at android.app.ActivityManagerNative.getDefault(ActivityManagerNative.java:76)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:84)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

08-25 15:44:26.989 E/ServiceManager( 1682): 	at dalvik.system.NativeStart.main(Native Method)

08-25 15:44:26.989 I/Process ( 1682): Sending signal. PID: 1682 SIG: 9

08-25 15:44:26.989 E/AndroidRuntime( 1682): *** FATAL EXCEPTION IN SYSTEM PROCESS: main

08-25 15:44:26.989 E/AndroidRuntime( 1682): java.lang.AssertionError: No server socket?

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at com.koushikdutta.vysor.Main.main(Main.java:302)

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at dalvik.system.NativeStart.main(Native Method)

08-25 15:44:26.989 E/AndroidRuntime( 1682): Error reporting crash

08-25 15:44:26.989 E/AndroidRuntime( 1682): java.lang.NullPointerException

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:84)

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

08-25 15:44:26.989 E/AndroidRuntime( 1682): 	at dalvik.system.NativeStart.main(Native Method)
...


08-25 15:44:27.069 E/ACodec  ( 1378): [OMX.amlogic.video.encoder.avc] ERROR(0x80001001)

08-25 15:44:27.069 E/MediaCodec( 1378): Codec reported an error. (omx error 0x80001001, internalError -2147483648)

08-25 15:44:27.069 E/StdOutDevice( 1378): Encoder error

08-25 15:44:27.069 E/StdOutDevice( 1378): java.lang.IllegalStateException

08-25 15:44:27.069 E/StdOutDevice( 1378): 	at android.media.MediaCodec.releaseOutputBuffer(Native Method)

08-25 15:44:27.069 E/StdOutDevice( 1378): 	at com.koushikdutta.vysor.StdOutDevice$Writer.encode(StdOutDevice.java:59)

08-25 15:44:27.069 E/StdOutDevice( 1378): 	at com.koushikdutta.virtualdisplay.EncoderDevice$EncoderRunnable.run(EncoderDevice.java:120)

08-25 15:44:27.069 E/StdOutDevice( 1378): 	at java.lang.Thread.run(Thread.java:841)

08-25 15:44:27.069 I/OmxComponent(  117): OMX.amlogic.video.encoder.avc: flush input

08-25 15:44:27.069 I/OmxComponent(  117): OMX.amlogic.video.encoder.avc: flush output

08-25 15:44:27.069 W/GraphicBufferSource(  117): Dropped back down to Loaded without Executing

**Comment by Wargazm** [comment]
1.0.3.8 works!  I did have to do `adb kill-server` and then force a reconnect, but it's working for me.

**Comment by DennisLfromGA** [comment]
When I first tried it I got the 'spinning logo' but now it won't connect anymore.

I *am* connected to my device (Samsung GS3) and can run adb commands on it but when I try to invoke Vysor it says: 'No devices found' and clicking on 'Choose a device' or 'No devices found' doesn't do anything.

![image](https://cloud.githubusercontent.com/assets/3418772/9478501/567c0d48-4b46-11e5-8faf-f88fe8ff3323.png)

**Comment by DennisLfromGA** [comment]
A 'Find device' button is momentarily displayed when I first invoke Vysor but then it immediately shows the image above and won't connect.

**Comment by koush** [comment]
@DennisLfromGA try disabling and reenabling the extension. the find devices button goes away if you're using your own adb, in which case it autmatically finds them.

**Comment by DennisLfromGA** [comment]
> the find devices button goes away if you're using your own adb, in which case it autmatically finds them.

I wish I understood what that meant ;) I'm afraid this is my first venture into 'adb' land...

I did disable/re-enable the extension and even removed/re-installed it but I still get the 'No devices found' display.

The file manager pops up when I insert my phone so it's getting mounted and adb reports the device serialno. Is it okay to leave the file manager open and the device mounted?

Sorry if these are dumb questions, If I/we can't get it figured out I'll wait 'til it's out of beta...

**Comment by sympathy4all** [comment]
@koush With the latest version 1.0.3.8, it works.

**Comment by samsoft00** [comment]
the first time, i got a spinner logo.. after running adb kill-server and reload... it display this
http://i.imgur.com/D8OTGIY.png

USB Debbuging mode is enable
Missing out anything?

**Comment by koush** [comment]
can you tag me in a post on Google+ and I'll send you a hangout invite so we can chat further.

**Comment by Aceofspades25** [comment]
How do I get this working? I'm running windows 10. 

I have a working ADB installed because I can browse my phone from my computer.

It's in PTP mode.

Vysor just says "No devices found" ([screenshot](http://i.imgur.com/Ck2pXPp.png))

I've tried restarting Vysor by enabling and disabling the chrome extension, restarting my phone. 

I have an LG G4

Any suggestions?
