### ISSUE TITLE
Return/Enter key function changed v1.0.7.x 

### ISSUE THREAD

**Issue by KevDoy** [koush/vysor.io#161]
Ever since Vysor updated, it appears that the return and enter key, despite the app just jump to the next line. Examples where to try this: Google Search field, Hangouts, and other stock apps. Can this go back to representing the button on the bottom right on the on-screen keyboard? (Search, Send, etc)? Toggle?

Android N Beta (05-19)
Vysor v1.0.7.3

**Comment by mathewng** [comment]
- Press **Manage Key Bindings and Navigation Bar** link
- Look for the "Enter" line.
- Change the line
from     ``"Enter": "KEYCODE_ENTER",``
to ``"Enter": "FLAG_EDITOR_ACTION",``

**Comment by koush** [comment]
oh nice @mathewng I was just looking to see if there was a way to do this.
Does this retain enter behavior on multiline text input?

**Comment by mathewng** [comment]
Actually,  it does. Pressing "Enter" will go to the next line for HTML textarea. 

Important thing for me is,  I can finally search in Google play store by typing and pressing "Enter"  with FLAG_EDITOR_ACTION. 

Whereas for KEYCODE_ENTER,  pressing the Enter key in play store search box will result in searching the top-most suggestion, despite what you actually type into the search box.

**Comment by koush** [comment]
@mathewng very cool, thanks. I will change the default key bindings.

**Comment by EricDube** [comment]
With FLAG_EDITOR_ACTION set as the Enter key mapping I can no longer submit text for messaging apps using the Enter key. Hangouts, Allo, WhatsApp and Messenger are putting a space instead of submitting, but do respond to KEYDOWN_ENTER as expected.

With FLAG_EDITOR_ACTION, chrome browser seems to be just removing the autocompleted part of the URL and not submitting, same with Google Play. I'm not entirely sure if this is how the FLAG_EDITOR_ACTION is supposed to work but it makes using the Vysor keyboard pretty much useless as you now have to click on enter to do any sort of send.

Am I using it wrong or is there an issue?

**Comment by mathewng** [comment]
You are right.
I use FLAG_EDITOR_ACTION with google keyboard and xperia keyboard and it works very well.
I have just tried FLAG_EDITOR_ACTION with vysor keyboard and the key is next to useless.

**Comment by EricDube** [comment]
Alright so maybe it's a Vysor keyboard issue instead of a binding issue. I can see what you meant with the binding using stock keyboard, I've been using Vysor to get rid of the autocorrect and get more real-estate.

**Comment by koush** [comment]
@EricDube I'll check vysor keyboard. that has different key event implementation.

**Comment by koush** [comment]
@EricDube @mathewng i looked into this. FLAG_EDITOR_ACTION is working due to dumb luck. The input is considered not mapped, and the default is to send the character across, which is carriage return. This value is being properly interpreted.
I have a fix coming for both International Keyboard and regular input.

**Comment by jareboomafoo** [comment]
I tried this and it didn't work :S 
![image](https://cloud.githubusercontent.com/assets/3615202/20635632/8f179dc0-b32d-11e6-8312-8afb2367fbd5.png)

**Comment by koush** [comment]
Yeah, don't use that anymore. Just reset key bindings and it will work.

**Comment by seanfrisbey** [comment]
This problem still seems to be present.  It works fine with Hangouts, but Messenges still just puts a new line (and a space, which I have submitted in another issue).

**Comment by CheloARG** [comment]
@koush sorry to revive this but I can't make the "enter" key work properly. If "international keyboard" is checked, pressing enter places a blank space, like using "spacebar". Ctrl + enter puts a new line. 
Thanks for any help you can bring, I'm using Vysor Pro on Windows 10 and my phone is a S7 edge.
