### ISSUE TITLE
Vysor's "Hide Keyboard" misbehavior with locked screen

### ISSUE THREAD

**Issue by SgtSeppel** [koush/vysor.io#178]
I just noticed the new option to let Vysor hide the keyboard. This is working great. Also, special chars now seem to work.
But I noticed, that I can no longer unlock the phone by entering the PIN on my PC keyboard.
When I turn on the display and enter the pin, it is not consumed by the lock screen. 
I have to manually enter it on the screen or with the mouse.
When the phone is unlocked I can then see that the numbers I tried to enter before are written into the last textbox that was selected (i.e. WhatsApp)

**Comment by koush** [comment]
Yeah, I've noticed this too. I'll fix it.

**Comment by jonathannz** [comment]
Sorry to chime in with a question on an issue report... but this is the only reference I found online to Vysor and "hide keyboard". I was looking online to find out how I can hide the keyboard. Based on this issue post, I assume it's possible. But how?
Thanks.

**Comment by tjman84** [comment]
You didn't fix it

This "feature" vysor keyboard makes the entire app pointless. I've tried disabling or removing the keyboard but am unable to. 

Not everyone needs to ever hide the keyboard and frankly, if my phone is basically disabled until I screw with turning the keyboard on and off for a minute every single time I unlock my phone, i can't use this app which works fine for everything else.

Please, PLEASE allow for the"vysor keyboard" to be disabled...

**Comment by koush** [comment]
You've been able to disable this feature since it has been released...
http://i.imgur.com/cK4yemS.png

**Comment by tjman84** [comment]
........... In no way is that clear

International keyboard? Seriously?

**Comment by koush** [comment]
That keyboard is required for international character input-- stuff outside the ASCII character set. So yes, international keyboard. Pretty clear.

**Comment by koush** [comment]
It's also not enabled by default.

**Comment by tjman84** [comment]
No where did I enable "vysor keyboard" and yet the lock screen isn't
responsive most of the time whether it's selected or not, until I switch
back and forth several times. See attached...I have multiple keyboards yet
only vysor keyboard intrudes into the lock screen...

**Comment by tjman84** [comment]
Not to mention also I don't think you caught my meaning in the previous
exchange:

"That keyboard is required for international character input-- stuff
outside the ASCII character set. So yes, international keyboard. Pretty
clear"

Ok, so you're example showed nothing that says *vysor keyboard*, you're
example has only one choice, international keyboard. In what way is it
clear from that page that those options will disable the vysor "hide
keyboard" "feature".

I mean literally, to someone that didn't work on the project, how would
that be evident?

You just scoffed, like "well yes the intentional keyboard is crucial! Of
course it's clear!" What's clear, that it's needed? How about does that
option remove the hide keyboard feature? I don't think that's at all
apparent.

.....dot dot dot

**Comment by koush** [comment]
You seem upset.

**Comment by koush** [comment]
@tjman84 

Look, I get it. It's embarrassing to come in here and shit on the developer and claim something is broken and that you can't fix it. Only to discover that you caused it yourself by fiddling with settings. And that the fix you wanted was in plain sight.

Next time, I'd recommend not being such a dick from the get go.

Maybe just say "oh, instead of calling it International Keyboard, have some help text or a tooltip under it so others do not get confused". Or "perhaps rename the IME in Android to Vysor International Keyboard".

Both of those would have worked.
