### ISSUE TITLE
Black screen after updating to Windows 10 1607 Aniversarry update 2016.

### ISSUE THREAD

**Issue by wcalderw** [koush/vysor.io#198]
After updating to windows 10 Pro 1607 the ability to display the screen of the connected device is no longer working. I can still control the connected device through vysor though.

**Comment by zonefish** [comment]
I also have this issue, but i can't tell if the reason was a Windows update. I can still control the connected device through Vysor, but the Vysor Window is just a black tile.

I am using Windows 10 Pro Version 10.0 Build 10240, Chrome Version Version 52.0.2743.116 m, Vysor Version 1.1.3.8 and Android 6.0.1 on a Nexus 5X.

![vysor](https://cloud.githubusercontent.com/assets/19939588/17712502/7fee2ce6-63f6-11e6-9b63-ffcecd4032cc.PNG)

**Comment by YieldNull** [comment]
Navigate to chrome://components and find pnacl. If the version listed is 0.0.0.0, update it.

References:

https://support.asperasoft.com/hc/en-us/articles/216126728-Corner-case-Connect-issues-on-Chrome-45-and-higher#pnacl-files

https://github.com/koush/vysor.io/issues/45

**Comment by koush** [comment]
Use the support link. There's troubleshooting for this issue.
