### ISSUE TITLE
Size and density messed up the phone display

### ISSUE THREAD

**Issue by jidesoft** [koush/vysor.io#219]
I was playing with the size and density setting and it messed my phone screen display completely and now I can't reset it back even after rebooting the phone. The status bar and the navigation bar is so tiny now. Please help! Thanks.

**Comment by koush** [comment]
Just use reset display settings.

**Comment by sonthonax** [comment]
This same thing just happened to me. However, I cannot just reset display settings. I restarted the phone after it went tiny and since then I've been stuck. Your chrome app says to turn on debugging but whenever I somehow click on the settings icon, nothing loads. I don't have any access to my settings. All my other apps and music yes. Can you please help me with this? Thanks.
