### ISSUE TITLE
Vysor - distribution for Linux (AppImage/Snaps)

### ISSUE THREAD

**Issue by koush** [koush/vysor.io#242]
Update:

Continuous builds can be found here:
https://github.com/koush/vysor.io/releases/tag/continuous

These app images will not autoupdate.

To do:
Prompt user within Vysor to download app image, when a new native runtime version is released.

**Comment by kles4enko** [comment]
It's sadly... I hope rpm will be available soon. ;)

**Comment by noraj1337** [comment]
Maybe an archive with source or a jar file too.

**Comment by noraj1337** [comment]
Vysor doesn't support Linux. It only supports Ubuntu, that's not the same.

**Comment by gerardo-junior** [comment]
+1

**Comment by gelldur** [comment]
Waiting for AUR :)

**Comment by lcastropg** [comment]
I've tried use the chrome one. It runs perfectly in Windows, but in the Linux (Fedora) I could not use. Waiting for it.

**Comment by jesse5817** [comment]
the shirt

**Comment by merrickluo** [comment]
I created a AUR package here.
https://aur.archlinux.org/packages/vysor/

**Comment by koush** [comment]
I'm not familiar with linux repos. What all must I do to publish a deb or rpm? preferably automatically in the distributions built in store? The last thing I want to do is have to publish to multiple linux distributions every time I create a build.

**Comment by kles4enko** [comment]
As linux user (any distro) the best way to use third-party software (which not included in the distribution) is custom repository from application owner.  For instance Visual Studio Code: https://code.visualstudio.com/docs/setup/linux

To use custom repo I need to add it ones, then install the app. If repo owner push update my package manager will see it with next refresh and notify me about existing update. 

Slack, Skype, Google Chrome, Visual Studio Code adding their repository automatically since you install it. I think it is also user friendly step. I need to download the app form the site, install it ones, then it will be auto-updated my default package-manager.

Will be great if you can provide both deb and rpm repositories. RPM is industrial standard for linux. On the other hand Debian-based distributions also popular.

Frankly, I have no experience with supporting custom repos. Can't help here ((

**Comment by anantshri** [comment]
Hi Koush, 

I am trying to create package for vysor (To be specific a deb package to be usable in debian / ubuntu distributed by repo.androidtamer.com ). the best approach i can think of is to have two packages one specifically for electron-chrome and second for vysor which basically relies on electron-chrome package and allows us to call the app id specifically. that ways we can update electron-chrome when anything new comes up otherwise we can keep pulling updates via appstore using the appid option.

However before i proceed with that route, during my limited research multiple other points came in light and just wanted to see if there was any discussion around them.

1. electron version used in electron-chrome seems to be older 1.6.X latest version available seems to be 1.7.X. Any specific reasons for sticking with older version.
2. hackernews debate pointed t nw.js as something that could be used. https://news.ycombinator.com/item?id=12374432  and nw.js seems to have support for chrome apps also. https://nwjs.io/blog/chrome-apps-support/ (I can see it doesn't allow for direct app id listing rather you need the app locally available)
3. the idea of seperately bundling electron-chrome comes in mind coz we might be able to use electron-chrome seperately to run other apps also. (do you have any list of what apps are usable via electron-chrome)
4. going forward i would be tracking the repository of electron-chrome and if and when you make a new release i will publish it on the repository of mine.

Note: I feel i have questions mixed for both vysor as well as electron chrome feel free to move discussion to different repository if that's what you feel will benefit more. and feel free to point reference links in case you have already answered the questions somewhere. (my limited google skills failed me on this hence asking)

**Comment by SachaYuri** [comment]
Chromium can be used?

**Comment by konradtrejo** [comment]
donde esta la version para ubuntu gnome  :( 
 q sed

**Comment by lunarcloud** [comment]
I'd settle for an AppImage version or a tarball...

**Comment by arroyoc** [comment]
What is the status on this? The vysor download page has a link for "linux" but takes me to this page. I don't see a way to download this for linux, more specifically Ubuntu 18.04.
I'de rather not use chrome at all. I'm guessing at this point in time that is the only solution for using Vysor with Ubuntu.

**Comment by konradtrejo** [comment]
Ubuntu 16.04 LTS

**Comment by trite2k3** [comment]
Slackware-current

Install nodejs and npm2tgz from sbopkg

git clone https://github.com/koush/electron-chrome.git
cd electron-chrome/
npm i npm@latest -g
npm install

/home/user/vysor/electron-chrome/node_modules/.bin/electron . --app-id=gidgenkbbabolejbgbpnhbimgjbffefm

Thanks it works now.

**Comment by L3vi47h4N** [comment]
Considered giving us a flatpak/appimage? Would save on the whole "needing to make a distro-specific package" bit. \*shrug\*

**Comment by Zarnaik** [comment]
@trite2k3 How did you get it to work? I was able to launch it, and connect my phone. The phone-screen isn't visible though, because electron doesn't support the PNaCl plugin that Vysor uses. This is the reason I tried the electron route, as chromium doesn't support it.

@koush (How) have you made it work on your end?

**Comment by jacobywu** [comment]
more +1

**Comment by trite2k3** [comment]
@Zarnaik Did you allow mtp connection on popup in android? enable usb debugging and stuff like that? I tried this on stock samsung android rom and custom rom with xposed framework and it worked on both.

I have a new install of Slackware atm and is doing exactly the same things now so well see if it works. This time its stock samsung rom

**Comment by nicocarbone** [comment]
Please consider an snap package

**Comment by maetthew** [comment]
+1 for any kind of package for Ubuntu

**Comment by VhMuzini** [comment]
+1 still waiting

**Comment by koush** [comment]
@merrickluo thanks for doing that.

For everyone else, I briefly looked at creating a Ubuntu package, and ran into some immediate blockers. But it was a while, and now I can't remember what it was. I'll reinvestigate this weekend and see what I can come up with.

**Comment by anupam-git** [comment]
@koush I am a fan of Vysor and have been using your products for a long time.
ClockworkMod was my favourite Custom Recovery. :smile: 

I would be happy to help you regarding this project. :heart: 

Currently I am using Vysor with a Chromium snap and snaps seems to have issues with finding flash plugin. Hence I an unable to use with Chromium snap. A native build would be so much helpful.

I can help with building `deb`, `rpm` and [`AppImage`](https://appimage.org/) packages.

**Comment by maetthew** [comment]
@koush @anupam-git C'mon do it! :D

**Comment by 1pvtxda** [comment]
I"d vote for deb package for ParrotOS and OR Kodachi OS. AND IF I COULD pay with paypal for the one year, as I tried to pay the 1yr.... and app says don't use paypal for this blah, blah so I can you take a Paypal donation and apply it to a year's worth of Vysor Pro, or start accepting Paypal for the Yearly, and OR... just make the PRO price $11 to cover Paypals's charges???? HUMMMM?

**Comment by HEXcube** [comment]
Compared to conventional Linux packages like deb, rpm, etc, modern formats like flatpak, snap or AppImage might be better in the long run, both from end-users' and developers' perspective. With Flatpak you can publish to FlatHub and with snap to Ubuntu Store, which makes installation a lot easier for regular users. They can just open the built-in Software app, find Vysor and install it rather than go hunting for distro-specific packages and custom repos from online sources.

**Comment by h0ek** [comment]
Would be cool to have a Linux package.

**Comment by 1pvtxda** [comment]
Yes it would be.....
beyond "cool" it would be super duper "cool" to state the least! 
Since Windows is one of the most "insecure" OSs on the planet, and running vysor / on Parrot OS, or Kodachi Linux would be a "heightened dream" of dreams especially running over USB rather than relying on WIFI or Bluetooth.

What was also "cool" was you being so kind as to "ask?" What we call in the old times "that was in the groove.. cool."

Be healthy,  and prosper others as you are doing, and that would be even "cool."

March 24, 2019 9:21:41 AM CET hoek <notifications@github.com> wrote:
Would be cool to have a Linux package.

**Comment by infowarz** [comment]
OPPS how do I "EDIT" that last post that posted from my email Notice???

**Comment by christianmtr** [comment]
> I created an AUR package here.
> https://aur.archlinux.org/packages/vysor/
> 
> Edit: renamed to https://aur.archlinux.org/packages/vysor-git/

I tryed installing those repos, but the both shows me black screen with Xiaomi Mi A1.

**Comment by maetthew** [comment]
> > I created an AUR package here.
> > https://aur.archlinux.org/packages/vysor/
> > Edit: renamed to https://aur.archlinux.org/packages/vysor-git/
> 
> I tryed installing those repos, but the both shows me black screen with Xiaomi Mi A1. The black screen can controls the phone.

Same behaviour here.

**Comment by djstkg** [comment]
I tried Vysor in Chromium on Ubuntu 18.04 LTS.

Screen is "This plugin is not supported" but it can control the phone.

**Comment by Skylead** [comment]
Still getting a black screen for this

**Comment by Gryzor** [comment]
I get this plug-in is not supported on Chrome now. (not Chromium). Pop!_OS 19.04 (Basically ubuntu)

**Comment by infowarz** [comment]
> I"d vote for deb package for ParrotOS and OR Kodachi OS. AND IF I COULD pay with paypal for the one year, as I tried to pay the 1yr.... and app says don't use paypal for this blah, blah so I can you take a Paypal donation and apply it to a year's worth of Vysor Pro, or start accepting Paypal for the Yearly, and OR... just make the PRO price $11 to cover Paypals's charges???? HUMMMM?

So.... I'd love to use this app, so what was wrong with the above suggestion? 
Some of use who use "high security" Custom Roms on "our" droids, don't do goo-girl play nor any goo-girl's any apps on "our" enterprise secured phones.
How about making the PRO year at $12 usd? OR $13
What would U'd be loosing?

**Comment by Capitalmind** [comment]
So where are the binaries?

**Comment by mritalian** [comment]
I get:

`symbol lookup error: [...]/ElectronChrome/crx/gidgenkbbabolejbgbpnhbimgjbffefm/app-2.1.7.crx-unpacked/native/linux/video_decode.so: undefined symbol: _ZN2pp3VarC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

Which demangles to:

`pp::Var::Var(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`

Still no closer to understanding why it fails.  Next I will try **wine**.

**Comment by xbao** [comment]
Same issue and OS as @Gryzor. 

@koush I (and apparently many others) would love some linux support if you've got the time :) Still paying the pro subscription, hoping you'll add support :crossed_fingers:

**Comment by koush** [comment]
I need someone to test this. Creating a Snap package in Ubuntu. Requires npm and node installed (which should be available already if you're here and using Vysor):

```sh
git clone https://github.com/koush/vysor.io
git clone https://github.com/koush/electron-chrome
cd electron-chrome
npm install
npm run package-linux -- --app-dir=../vysor.io/public/app/
node_modules/.bin/electron-builder --project build/
```

AppImage will be in electron-chrome/build/dist

Let me know!

**Comment by koush** [comment]
Actually, here's the AppImage file I built:

https://github.com/koush/vysor.io/releases/tag/2.1.2

**Comment by koush** [comment]
My testing indicates that the icon does not show up in the launcher (but clicking the appimage works).

**Comment by anupam-git** [comment]
I tested the AppImage on my Ubuntu 18.04 with the following specs : 
```
**OS**: Ubuntu 18.04.2 LTS x86_64 
**Kernel**: 4.15.0-50-generic 
**DE**: Xfce 
**WM**: Xfwm4 
**CPU**: AMD Ryzen 5 1600 (12) @ 3.200GHz 
**GPU**: NVIDIA GeForce GT 1030 
```
1. The `Find Devices` button is missing when ADB Server is not running
![image](https://user-images.githubusercontent.com/5106648/59737145-18b9b580-927a-11e9-844f-6a2f0c972b69.png)

2. After starting the ADB Server, vysor needs to be closed and reopened to list the devices
![image](https://user-images.githubusercontent.com/5106648/59737288-a4cbdd00-927a-11e9-96ed-81eab6ad9c92.png)

3. On trying to view the device, the window opens but appears black. Still the touch inputs and the buttons are working fine. This issue was still there when I tested with `electron-chrome` directly.
![image](https://user-images.githubusercontent.com/5106648/59737386-14da6300-927b-11e9-9c49-ccfc1d0b6e80.png)

**Comment by koush** [comment]
@anupam-git thanks I think I have fixes for all of those and will release something later today.

**Comment by anupam-git** [comment]
@koush Welcome.. :)

And let me send a PR to build this Appimage in TravisCI and automate the build and publish process.

**Comment by Skylead** [comment]
App image is running on arch, window resizes for proper aspect ratio and button/clicks work but still black. Will test update later today

**Comment by koush** [comment]
@anupam-git @Skylead I have updated a second appimage:
Vysor.2.1.7-beta2.AppImage

This starts up adb properly and also fixes the black screen issue.
The resultant snap image (which you can build yourself) does not work. It gets a graphics context null. I'm unsure why. I think it may be a snap permission or packaging issue.

The appimage still doesn't include a launcher icon. If someone knows how to fix this (pull requests preferred, look at package.js), please do.

**Comment by xbao** [comment]
Just trying it out, so far works perfectly! I can see and control the screen (at least of the emulator). Thanks so much! This is on Pop!_OS 18.10

**Comment by anupam-git** [comment]
@koush I tested the **2.1.7-beta2** release.

1. `adb` is getting started successfully
1. Black screeen issue is solved now, I can see the screen now.
1. I can see that the launcher icon loaded correctly, no issues here
![image](https://user-images.githubusercontent.com/5106648/59815416-216fc180-9336-11e9-81db-2b64d5efa436.png)

**Comment by Gryzor** [comment]
I tried the 2.1.7-b2 appImage and it didn't necessarily start ADB for me (no button) as soon as I fired an emulator, the UI updated and it worked. Looks promising.

**Comment by koush** [comment]
@anupam-git I see the icon in the task bar, but when I search for Vyso in the app launcher (windows button), nothing shows up. Is  case for you?

**Comment by anupam-git** [comment]
@koush I used the official [`appimagelauncher`](https://github.com/TheAssassin/AppImageLauncher) to integrate into the system and that successfully integrated the icon too.

Here is the entry as shown in **XFCE Whiskers Menu** :
![image](https://user-images.githubusercontent.com/5106648/59871209-98e43600-93b4-11e9-9de3-05b45de2140d.png)

**Comment by koush** [comment]
@anupam-git i see. on ubuntu, when i double click the app image, it prompts to integrate into the system, but does not seem to actually work. i'm not a heavy user of any linux distro so maybe i'm doing something wrong, or maybe their integration is just broken.

**Comment by anupam-git** [comment]
@koush Could you try with the above link I gave for the `appimagelauncher`? It should work.

And just out of curiosity, which OS do you use?

**Comment by koush** [comment]
@anupam-git I am a Mac user. I'll take a look at your link.

**Comment by koush** [comment]
> I tried the 2.1.7-b2 appImage and it didn't necessarily start ADB automatically for me (no button) but as soon as I fired an emulator, the UI updated and it worked. Looks promising.

Did you need to start adb manually then? When I was testing, I made sure my adb server was killed before starting Vysor.

**Comment by infowarz** [comment]
NU .exe working great on Windose 7Pro. 
But I still can't do goo-girl pay, as it's a "privacy" issue.

But thanks very much for your / everyone's work on this fine app!

**Comment by anupam-git** [comment]
@koush Hey.. I submitted a PR [#396](https://github.com/koush/vysor.io/pull/396) to automate building 
snap and appimage and push them to GitHub Releases using TravisCI..

**Comment by Skylead** [comment]
@koush Working great on Arch now confirmed (was out of town), Pro mode also working as expected. AR device support working as expected

Our team appreciates the fix

**Comment by Gryzor** [comment]
> @Gryzor
> 
> > I tried the 2.1.7-b2 appImage and it didn't necessarily start ADB automatically for me (no button) but as soon as I fired an emulator, the UI updated and it worked. Looks promising.
> 
> Did you need to start adb manually then? When I was testing, I made sure my adb server was killed before starting Vysor.

Nah, you're right, i did ` adb kill-server` before double clicking the appImage just to make sure. Once opened, Vysor fires adb automatically. 

I didn't chose "yes" to integrate it with the OS, but it works (albeit the icon is a "gear" as opposed to the Vysor icon)

**Comment by koush** [comment]
@anupam-git thanks for that. I've got continuous builds for AppImage here now:
https://github.com/koush/vysor.io/releases/tag/continuous

**Comment by anupam-git** [comment]
@koush Awesome.. :+1: :+1:

**Comment by pemgithub** [comment]
On Ubuntu 18.04, I got the chrome add-on to work, but "Vysor_2.1.7.AppImage" gives a black screen
![image](https://user-images.githubusercontent.com/13956322/67994608-49840100-fc03-11e9-81f1-a45036da6a60.png)

**Comment by maheshmnj** [comment]
so is there any simpler way to install vysor on ubuntu 18.04?

**Comment by maheshmnj** [comment]
> ```shell
> node_modules/.bin/electron-builder --project build/ --linux snap
> ```

thank you very much I ran through this step by step works perfectly for ubntu 18.04 and I did not require any app on the mobile phone will share my experience and issue if any after using this ,thank you very much you made my day

**Comment by maheshmnj** [comment]
> I need y'all to test this. Creating a Snap package in Ubuntu. Requires npm and node installed (which should be available already if you're here and using Vysor):
> 
> ```shell
> git clone https://github.com/koush/vysor.io
> git clone https://github.com/koush/electron-chrome
> cd electron-chrome
> npm install
> npm run package-linux -- --app-dir=../vysor.io/public/app/
> node_modules/.bin/electron-builder --project build/ --linux snap
> ```
> 
> Snap install as follows (unsigned):
> 
> ```
> sudo snap install --dangerous build/dist/Vysor_2.1.7_amd64.snap
> ```
> 
> AppImage will be:
> 
> ```
> build/dist/Vysor 2.1.7.AppImage
> ```
> 
> Let me know if the output works!
> 
> Assuming this works, I'll get it published somewhere, once I figure that out as well...

thank you very much I ran through this step by step works perfectly for ubntu 18.04 and I did not require any app on the mobile phone will share my experience and issue if any after using this ,thank you very much you made my day

**Comment by vitich** [comment]
I tried the versions Vysor_2.2.1_amd64.snap and Vysor_2.3.0_amd64.snap but still get a black screen ...

**Comment by ak2766** [comment]
Tried this on Ubuntu 16.04.6 LTS.

When running it via electron:
`$ node_modules/.bin/electron --project build/ --linux snap`
it works fine.  See the logs [here](https://pastebin.com/divPEhHh).

When running it as an application:
`$ vysor`
it gives me a black (sad face) screen.  See the logs [here](https://pastebin.com/UGkUrrpn).

**Comment by AniketSK** [comment]
Hello, I got the zip file, I'm on Linux and it's not really how to run this? Because of other issues, npm is broken on my machine. I see it's an electron app and perhaps npm start is supposed to begin it but that doesn't work.

How exactly am I supposed to launch Vysor if I've got the zip file?

**Comment by 1pvtxda** [comment]
February 25, 2020 7:17:47 AM CET Aniket Kadam <notifications@github.com> wrote:

Hello, this is the email.... that this thread is issued to...pvt1eye@mailfence.com

 I get NOTICES to, I am NOW living in a country to the whatever that @me.com ???????????????????

PLEASE STOP ALL EMAIL as I am NOT doing anything that requires any NOTIFICATIONS to this address!

BESIDES I would NOT use Vysor on your computer and or your phone, as I don't LIKE the "PRIVACY TERMS," at ALL!

So PLEASE STOP since I can' sign in NOR get a password reset, but this is the email account that I want "NOTIFICATIONS" STOPPED!

THANK YOU!

 

Hello, I got the zip file, I'm on Linux and it's not really how to run this? Because of other issues, npm is broken on my machine. I see it's an electron app and perhaps npm start is supposed to begin it but that doesn't work.
How exactly am I supposed to launch Vysor if I've got the zip file?

**Comment by vitich** [comment]
STOP IT YOURSELF

--
WBR, vitich@gmail dot com


ср, 26 лют. 2020 о 02:19 1pvtxda <notifications@github.com> пише:

**Comment by bathan** [comment]
@1pvtxda Have you tried turning it off and on again?

**Comment by fmatosqg** [comment]
> On Ubuntu 18.04, I got the chrome add-on to work, but "Vysor_2.1.7.AppImage" gives a black screen
> ![image](https://user-images.githubusercontent.com/13956322/67994608-49840100-fc03-11e9-81f1-a45036da6a60.png)

I get that with snap 2.2.1 but running with AppImage works. It did fail at first with a black screen but no popup and error message, but connecting again worked.

Linux Mint + Cinnamon
> lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Device 591b (rev 04)
> inxi -G
Graphics:
  Device-1: Intel driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 3200x1800~60Hz, 3840x2160~30Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2) 
  v: 4.5 Mesa 19.2.8 

As you can see there's no nvidia here, so the support page is not helpful.

For the unaware on how to run AppImage like me, I did `chmod a+x Vysor_2.2.1.AppImage` then `./Vysor_2.2.1.AppImage`

Thanks for the packaging :)

**Comment by occultus73** [comment]
> > On Ubuntu 18.04, I got the chrome add-on to work, but "Vysor_2.1.7.AppImage" gives a black screen
> > ![image](https://user-images.githubusercontent.com/13956322/67994608-49840100-fc03-11e9-81f1-a45036da6a60.png)
> 
> I get that with snap 2.2.1 but running with AppImage works. It did fail at first with a black screen but no popup and error message, but connecting again worked.
> 
> I have no idea how to run the npm or else I could try and add some logs here.
> 
> Linux Mint 19.3 + Cinnamon
> 
> ```
> > uname -a
> Linux fabio-mint-5520 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> 
> > lspci | grep VGA
> 00:02.0 VGA compatible controller: Intel Corporation Device 591b (rev 04)
> > inxi -G
> Graphics:
>   Device-1: Intel driver: i915 v: kernel 
>   Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
>   resolution: 3200x1800~60Hz, 3840x2160~30Hz 
>   OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2) 
>   v: 4.5 Mesa 19.2.8 
> ```
> 
> As you can see there's no nvidia here, so the support page is not helpful.
> 
> For the unaware on how to run AppImage like me, I did `chmod a+x Vysor_2.2.1.AppImage` then `./Vysor_2.2.1.AppImage`
> 
> Thanks for the packaging :)

I'm getting exactly the same error with a Radeon HD graphics card. The advice to utilise "Switchable Graphics Application Settings" because Ubuntu uses its own open source RadeonDriver software, not AMD Catalyst.

I'm guessing a **recent update** broke the code that handles graphics on Ubuntu.

**Comment by ZX183** [comment]
Hi,all
How to deal with this situation:



![Screenshot from 2020-04-26 17-25-12](https://user-images.githubusercontent.com/53074550/80303824-38e4ca00-87e5-11ea-9a4d-7ae1328a536f.png)

**Comment by NickZt** [comment]
With Ubuntu 18.04.4 LTS I can not start vysor: 
$ vysor
using chrome runtime 1.3.6
autoUpdater feed url https://vysornuts.clockworkmod.com/update/linux_x64/2.3.1
embedded /snap/vysor/x3/resources/app/unpacked-crx found
chrome runtime id lhaagglfcbekgaiedemenlgbkbhjepnk
chrome app id gidgenkbbabolejbgbpnhbimgjbffefm
chrome app directory /snap/vysor/x3/resources/app/unpacked-crx
/snap/vysor/x3/resources/app/unpacked-crx/native/linux/audio_playback.so not found.
/snap/vysor/x3/resources/app/platform-assets/linux/audio_playback.so not found.
PPAPI path /snap/vysor/x3/resources/app/unpacked-crx/native/linux/video_decode.so;application/x-ppapi-vysor
starting
registerprotocol
starting runtime
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(electron) 'setName function' is deprecated and will be removed. Please use 'name property' instead.
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
killing all windows for shutdown
chromeRuntimeWindow shutdown
windows remaining [
  BrowserWindow {
    setBounds: [Function],
    _events: [Object: null prototype] {
      blur: [Function],
      focus: [Function],
      show: [Array],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      close: [Array]
    },
    _eventsCount: 8,
    devToolsWebContents: [Getter],
    _maxListeners: 1000
  }
]
window-all-closed

**Comment by koush** [comment]
Locking this issue since it's resolved. Please open new issues as necessary.
