### ISSUE TITLE
Microsoft Visual C++ Runtime Library .. JIT must be enable

### ISSUE THREAD

**Issue by ewshadow** [koush/vysor.io#254]
I try to open my device view but got a black screen with Microsoft Visual C++ Runtime Library.

Anyone has a solution for that?
![c runtimelibraryerror](https://cloud.githubusercontent.com/assets/12925863/26635375/8fd27c88-45e7-11e7-8d58-f378f17c2040.PNG)

**Comment by Dragony** [comment]
Same Issue here:

![2017-06-06 14_29_55-neuer tab](https://cloud.githubusercontent.com/assets/465941/26829186/cf20dc04-4ac4-11e7-944c-189b17ccc9a6.png)

Vysor was previously working. Maybe it has something to do with the device? I'm using a HTC Ultra. I worked in the past with an HTC One m8.

**Comment by Zandemmer** [comment]
Unfortunately I had the same issue (never tried the program before). Retrying results in a black screen that allows me to interact with the phone but I can't actually see what I'm clicking. I'm using a Galaxy S8 running Android 7.0

**Comment by koush** [comment]
This issue happens when webgl hardware acceleration fails. Sometimes due to multiple monitors or multiple video cards (integrated vs discrete).

**Comment by Zandemmer** [comment]
I looked into the issue some more but I'm going to blame the poor performance of my graphics card on my laptop. It runs fine on my desktop.

**Comment by alexandersterlingrane** [comment]
The integrated vs. discrete card is where the issue lies. **I fixed this by running in compatibility mode with Windows 8 and running as administrator. Change these under the compatibility tab in the right-click menu.** I also switched my USB mode (in the drop-down menu of my Samsung Note) between all the modes respectively and let them install their drivers, ultimately ending up on the media transfer mode. Just wanted to add that in case it ended up helping anyone. -A

**Comment by istoff** [comment]
In addition to alexandersterlingrane's solution, I had to reset Vystor free version and then it worked.  I was able to reactivate my pro license and it has been working for the last hour or so.

Hope this helps.  For the record, I do have 2 video cards.  An onboard Intel and a crappy old AMD, so the discrete video might still be the issue.

**Comment by retardsroo** [comment]
Hello, I have the same Issue. I tried running compatibility mode but with no success. :( I tried to update drivers too. Do you please have any other suggestion? Thank you.

**Comment by retardsroo** [comment]
ok i just found out Vysor works in Google Chrome but not in Desktop application.... That is really weird.

**Comment by bettik** [comment]
Approaching 1 year later.  Any updates?  Dual graphics is standard for modern laptops.  I've gone through 3 different ones over the course of the last year and Vysor has had this issue on all of them.

**Comment by Vexamus** [comment]
I managed to get this working in Chrome, but what I had to do was go into chrome://flags and enable experimental WebGL extensions.  Now it works wonderfully.  Desktop still doesn't work.  Hope that helps!

**Comment by arya6000** [comment]
@Vexamus I'm also having trouble running Vysor and I don't have "experimental WebGL extensions"  in chrome://flags did they remove in the new version of Chrome?

**Comment by istoff** [comment]
@Vexamus 
Vysor Pro works on my Huawei P20 Pro over USB-C.
Chrome  67.0.3396.87 (Windows 10 64 Bit).

Checked the flags.  Found the following 
WebGL Draft Extensions  ( DISABLED )
Enabling this option allows web applications to access the WebGL Extensions that are still in draft status. – Mac, Windows, Linux, Chrome OS, Android

Hope you get it sorted.

**Comment by josiasfabricio** [comment]
Fix Desktop Version

1. Stop adb.exe (32 bits)
2. Delete Folder: C:\Users\user\AppData\Roaming\Vysor
3. Delete Folder: C:\Users\user\AppData\Local\Vysor
4. Use Windows 8 Compatibility Mode in Vysor-win32-ia32.exe
5. Run Vysor-win32-ia32.exe as Administrator

**Comment by haggardPL** [comment]
I wish there as more info on this issue. I bought an enterprise license for my team to start using this to test our Android app and it completely stopped working for me. I'm not too happy, I've tried about everything on here to resolve the issue and nothing has worked. I haven't been able to get the chrome extension to work either with the certain WebGL chrome flags having disappeared in this new version of Chrome.

@josiasfabricio I tired your method as well and it unfortunately did not work. I'm at a loss.

@koush  I'm using a Lenovo Yoga 720 with a dedicated Nvidia Gefore GTX 1050 and Intel integrated graphics on Windows 10. I'm also using two monitors hooked up to the laptop. What do I need to do to get this working?

**Comment by rsudasassi** [comment]
This problem was driving me crazy. It worked on one laptop but not the other (both running Windows 10). I ended up solving the problem by letting Windows troubleshoot for compatibility issues as follows:

1. Search Windows for Vysor app.
2. Right-click on Vysor app icon in search results and select Open file location.
3. Right-click on Vysor app icon (in Explorer) and select Troubleshoot compatibility.
4. Select Try recommended settings.
5. That fixed it for me, so I saved the settings.

Works fine now.

**Comment by dhiren71** [comment]
@rsudasassi :- This is working fine for me... thanks....

**Comment by gonzobrains** [comment]
Why is this bug being closed without any comment or solution?

**Comment by CaptainXLAB** [comment]
I can confirm multiple monitors cause this too. I have a desktop, single GPU, the same error on vysor desktop app (had it before in chrome but not anymore for whatever reason).

**Run it by physically plugging the other monitor out**, click "view" and it starts without problems, **plug the monitor back in and it works fine after that.**

(The created window sizes are just the titlebar after closing and re-opening but right click, size, increase size/resize, easy fix.)

**Comment by bhinderwalab** [comment]
Also try switching compatibity with windows 8 windows 7 , xp etc ...Run a compatibility troubleshoot(keep refreshing after every step)

**Comment by bhinderwalab** [comment]
> Why is this bug being closed without any comment or solution?

Lemme know if you need help with it , ive got mine solved

**Comment by gonzobrains** [comment]
That didn't work for me. What is the real fix?

**Comment by koush** [comment]
@gonzobrains please check app.vysor.io
I’ve removed the webgl and pnacl dependency entirely.

**Comment by gonzobrains** [comment]
Does this mean I need to download a new version?  BTW, how can I purchase
it with my personal account and then use it on a work computer?  I don't
want to put my personal credentials on my work computer nor do I want to
add a credit card to my test account I use at work.

**Comment by rrutkowski** [comment]
I had a similar issue. In my case, the system I was using was lacking the graphic card drivers. Installing the drivers manually solved the problem.

**Comment by atuldpatil** [comment]
In my case when I launched installed application (Vysor.exe) it was giving 
"Assertion failed! in video_decode.dll in File video_decode.cc at line 327 with Expression: result == PP_OK"

When I tried adding Chrome extension Vysor (from: https://chrome.google.com/webstore/detail/vysor/gidgenkbbabolejbgbpnhbimgjbffefm)
it gave error: "WebGL is not supported"

However I was seeing Vysor in chrome://apps/ and when I launched that and clicked "view" device, I got error:
"Error connecing to Android device. Vysor was unable to access the Android USB device. Vysor may be mirroring this Android in another tab"

Then I killed all running instances of "Vysor.exe" and then "adb.exe" and  from task manager. 

Then in Chrome I made these settings

Under: chrome://settings/
Use hardware acceleration when available: True


Under chrome://flags/ 
WebGL 2.0 Compute	Enabled
WebGL Draft Extensions	Enabled
Override software rendering list Enabled
Hardware-accelerated video decode (Already enabled)

Restart Chrome.

And now when I launched from here
chrome://apps/
It works like charm 
(However I am still getting assertion error if I try to launch Visor installed application (Vysor.exe). But since its working via Chrome extension, I don't care about it now)
