### ISSUE TITLE
Where is vysor's manual? (See also issue #263)

### ISSUE THREAD

**Issue by iiPostMaster** [koush/vysor.io#264]
The owner closed my issue telling me to look at the manual, but provided me with no link and didn't specify where I could find it.

**Comment by koush** [comment]
![vysor](https://user-images.githubusercontent.com/73924/28444472-4857c478-6d72-11e7-86b4-4d8e703a13c3.png)

**Comment by hypehuman** [comment]
This takes me to a page that says "Google+ is no longer available for consumer (personal) and brand accounts". I cannot find the manual anywhere.

**Comment by RonOnThePond** [comment]
Same here. Vysor is great, but support is lacking and without the manual ... so, where is it? Please give us an alternate link to access the Vysor user manual!

**Comment by Gwalior-84** [comment]
This issue has been marked as closed, but it is clearly not resolved.

**Comment by GreenBean4323** [comment]
Yeah, not to mention the manual should be plastered all over the downloads page and stuff so that people actually see it, instead of tucked away at the bottom of the page where nobody is gonna bother to look. Nice going there, very bright idea indeed. 🤔

**Comment by rjbeswin** [comment]
Manual please

**Comment by GreenBean4323** [comment]
Something else that's pretty damn funny is that the Google Docs file for the manual or whatever it was just got completely removed. There is no manual anymore unless someone else posts an unofficial download link somewhere else.
Vysor is going to hell. It broke my old phone permanently by changing the display in a way that couldn't be reverted while the phone was off and my phone ran into a bootloop trying to enter a tablet state so I couldn't do it while the phone was powered on either. I had to buy a brand new phone just because of this program, so Vysor technically made me lose 250 dollars.

**Comment by koush** [comment]
Foxed
