### ISSUE TITLE
Vysor kills running ADB

### ISSUE THREAD

**Issue by stevenjoy2013** [koush/vysor.io#270]
Running chrome version vysor 1.8.2 (1.7.2 has same problem) on Ubuntu 16.04

1. Run adb devices on ubuntu terminal (shows devices connected)
2. Run vysor from chrome, it shows connected devices but all disappeared suddenly
3. Run adb device on ubuntu terminal, shows something like "adb daemon not started, restarting"

I remember it works great old days, but I don't know when does this problem comes, any clue?

**Comment by anantshri** [comment]
as far as i remember. since vysor uses its own adb daemon that's why the existing daemon is killed and new one started. Would be good if it can check existing adb in path and use that. will allow for seamless interactions, a lot of times we want screenshare and at the same time we want to use adb on commandline to perform actions.

**Comment by stevenjoy2013** [comment]
I found it crashs adb when I attach 60 devices, if only attach 30-40 devices, it works good. Don't know why
