### ISSUE TITLE
Copy Paste from PC to Anroid (multiple line failed)

### ISSUE THREAD

**Issue by Nicky2999** [koush/vysor.io#293]
Hi sir ,

Im trying to copy paste from PC to the Android's vysor stimulator but its failed . Only single line can be copy and paste .. can you try to fix it or any other alternative ways to do multiple line coy paste  ? 

Thanks and best regards..
Nick

**Comment by koush** [comment]
I'll take a look

**Comment by tlhintoq** [comment]
@escarillex   Nope.
@Nicky2999   Just tried it today (01feb2019) (13months since initial report) - and it is still not possible to paste a line with a carriage return in it - making it impossible to paste more than one line at a time.

Test was copying a few lines from Notepad++ on the PC and pasting into ESNoteEditor on a Samsung tablet.

**Comment by Franzie** [comment]
re COPY AND PASTE from Windows 10 PC to Android. I used to be able to copy and paste 1 line, but no line returns, now it seems even the SPACE character is blocked, so no pasting of a few words with a space inbetween.
DRAD!
