### ISSUE TITLE
Rotation automatically unlocks when disconnecting

### ISSUE THREAD

**Issue by chaoren** [koush/vysor.io#297]
1. Lock rotation
2. Connect to device
3. Close window
4. Check device rotation setting

Happens with both wireless and usb connection.

**Comment by p1ho** [comment]
I can confirm this is still happening with usb connection. I think it should be fixed.

However, this scenario only happens if the window on your computer is closed before disconnecting.
If the device is disconnected directly without closing the window, the rotation setting doesn't change.

Catch: if the device is disconnected directly before closing the window, the input setting on the phone will still be Vysor, and requires manual effort to change it back to cell's input method.
