### ISSUE TITLE
Feature request: Reverse tethering

### ISSUE THREAD

**Issue by doubleo2** [koush/vysor.io#379]
This may be beyond the scope of Vysor, but the ability to reverse tether connected devices would be awesome.

I'm using Vysor with a bunch of test devices. Normally I go through my devices, one by one, and manually connect them to WiFI. I recently moved into an office where the WiFi has a captive portal that requires sms verification, which led me to discover [Genymotion's gnirehtet](https://github.com/Genymobile/gnirehtet). It allows you to share your computer's internet connection with your connected devices.

Building this functionality into Vysor would be awesome for people who use Vysor on the go - e.g. bouncing from coffee shop to coffee shop or giving presentations on the road.

**Comment by goelayu** [comment]
Reverse tethering would require root I guess. 

Instead of using a third party tool like gnirehet, I would recommend simply using the bash commands to set up ip route configurations and reverse tethering. Something like this https://forum.xda-developers.com/showthread.php?t=2287494&page=36 . Just create a bash script containing these commands.  And then every time you fire the vysor app from your shell, alongside you can run the reverse tethering script as well!
