### ISSUE TITLE
Clicking "Go Wireless" button does nothing

### ISSUE THREAD

**Issue by hypehuman** [koush/vysor.io#400]
When I press the "Go Wireless" button, nothing happens. I'm using the Windows version.

Begin rant:

I just purchased Pro so that I could use the Go Wireless feature and use my USB port for my speakers instead. Now clicking on the button does nothing. I tried looking on the Support page of the website, but there are only three questions and there's no way to ask a new question. The link to the manual is broken. I then looked at the Refund page, and it says "Chrome Web Store purchases are not recommended. Chrome Web Store purchases are not eligible for refunds." It would have been nice to tell me that before I purchased it. I actually tried purchasing it with PayPal first, but it said that PayPal payments are not accepted for that purchase. So I used the Chrome Web Store instead. And now there's no support and no refund.

Very unhappy.

**Comment by Neobond** [comment]
I also purchased Pro for the wireless option and higher quality video. I get an error message "is your Android connected Wifi?" It is and I tried both 2.4GHz and 5GHz neither work.

**Comment by hypehuman** [comment]
Oh, looks like the developer saw this issue and simply closed it without responding. I hope I can get them banned from the Google Play store.

**Comment by raphaelfuchter** [comment]
Same error here. Any solution?

**Comment by gittac** [comment]
I believe this developer has an awesome project.  What you have to remember
is every device is different and the developer is doing the best they can.
I find this doesn't work when you move from one wi-fi to another.  I find
if I connect through USB first and then click the little wi-fi symbol to
write of the word view and then disconnect the USB wire you will be on
wi-fi.  Then let's say you shut down your computer then when you go back to
connect that button you are talking about will work sometimes not.  So I
usually go to USB first as described above.  I am paying yearly because of
the high regard I have for this app.

**Comment by Neobond** [comment]
STFU shill it's c;lear the dev isn't interested in his clients.

**Comment by koush** [comment]
This was an old bug and has been resolved.
