### ISSUE TITLE
Audio Mirroring Not Working

### ISSUE THREAD

**Issue by edmundchu** [koush/vysor.io#418]
I am trying to mirror my audio through Vysor Pro
But pressing the audio mirror button only pops up Google Home
The audio is still not mirrored to my PC
I need a solution to this

**Comment by eeevp** [comment]
Hi, I have the same problem.
This is due to google updated home app not too long ago, so the mirror button would not work as intended.
My solution now is as following. 
1. Make the cast video shout cut from google home (by holding google home app). 
2. Hit the audio mirror button
3. Hit return to Home button
3. Then hit cast video shout cut before audio mirror button reappear again.
That should connected the audio.

Now, I have another problem with the audio mirroring.
My audio would randomly stop after I using them for awhile like 10 to 30 mins.
I would need to stop mirroring and start again in order to make it works again, which is very frustrated.
I really hope there's better support for this app.
The manual is even linked to a outdated google+ page......

**Comment by edmundchu** [comment]
Thank you so much
hopefully there will be more fixes to the issue

**Comment by tehwlof** [comment]
I'm facing the same issue since the last Google Home app update, except for the fact that now when clicking the audio mirror button, the Google Home app doesn't open up automatically anymore. The button just disappears for a few seconds and then reappears.

Any thoughts?

**Comment by tehwlof** [comment]
@koush any news from your side?

**Comment by EliasRanz** [comment]
There's more activity on #354

**Comment by koush** [comment]
Please test Vysor 2.2.2. https://github.com/koush/vysor.io/issues/426

**Comment by girlkelly** [comment]
my google home doesn't show 'mirror device' option so how do I get audio with my video?
