### ISSUE TITLE
Request: Don't bring Vysor main window to front on Dock icon click (macOS)

### ISSUE THREAD

**Issue by crouchingtiger** [koush/vysor.io#460]
First off, this is only a small nitpick. Vysor has proven to be invaluable to me, I purchased a lifetime licence within seconds of finding out about it. Thanks for creating this!

**Describe the bug**
On macOS, clicking the dock icon for Vysor will bring the Vysor main window to front even if you already have a session with a connected device. On a smaller laptop device, this often means it obscures your session window, and since the window doesn't respond to Cmd+W, it's an extra annoyance to manually close the window.

**To Reproduce**
1. Connect a device and start a viewing session.
2. Bring some other macOS window to the front (eg. Safari)
3. Click the Vysor Dock icon
4. The Vysor main window will pop-up a split second after the connected device window does, often obscuring the view of the connected device (on a smaller screen such as a laptop).

Note: This behaviour also applies if you use Alfred/Spotlight to relaunch or jump. 

**Expected behavior**
Add an option to disable the window being ordered to front when a device is connected, or some other logic.

Relevant API method: https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428638-applicationshouldhandlereopen

**Comment by koush** [comment]
I know exactly what you're talking about. This annoyed me too :)
I'll fix it. I have a major new release coming soon.

The reason this happens is because there's no way to open the main vysor window from the device mirroring windows. So it's possible to get into a state where it's not possible to bring the main vysor list up anymore.

I've fixed this by adding a new button that brings up the vysor list in the upcoming release. The old behavior of popping the list on dock click will be gone.
![Vysor](https://user-images.githubusercontent.com/73924/79302348-f3e59d00-7ea0-11ea-950d-1607a8f7ab26.png)

**Comment by crouchingtiger** [comment]
Excellent, thank you!

**Comment by koush** [comment]
Fixed in native prerelease. Would appreciate a test.
https://github.com/koush/vysor.io/releases/tag/v3.0.33

**Comment by crouchingtiger** [comment]
@koush Works great, and the high-resolution quality is so much better with the newer render engine (I connect via cable so network latency isn't an issue).

I had issues authenticating my licence via Safari (my default browser), solved it by launching the login URL in Chrome.

Just one small request: Could you please add an option to disable the NSStatusItem? I'm using Bartender for now to hide it from the menu bar for now as I don't really need it.

**Comment by koush** [comment]
Sure open I’ll another bug for that
