### ISSUE TITLE
Make the in-built title bar optional

### ISSUE THREAD

**Issue by alaricljs** [koush/vysor.io#47]
Can you make the title bar you recently added to the app optional?

**Comment by koush** [comment]
done, it fades out.

**Comment by kizer8** [comment]
How do you bring the title bar back up after it fades out?

**Comment by djpeinado** [comment]
The only way I found to show the title bar again is minimizing/restoring window.

Please, provide a 'pin' button to allow title bar to be always attached to window and visible as bottom buttons bar.
I find 'power button' very useful, I would like this button to be always visible, not in a translucent bar on top of screen that fades out.

**Comment by syedrakib** [comment]
Having to minimize/restore to show the title bar is annoying. I would prefer it to be pinned. But then pinning happens by overlapping the top notification bar. That kind of obstructs the view of the notification bar. Can it please be pinned on top but above the phone display instead of overlapping the phone display?
