### ISSUE TITLE
Your support site doesn't provide a way to report bugs

### ISSUE THREAD

**Issue by espertus** [koush/vysor.io#544]
I went to your support site to find information on a problem I was having. I was able to choose among 3 existing issues, not report a new issue. I was just given the option to start over, which sent me into an infinite loop.

You should provide information on your support page on how to report bugs, such as a link to your github site or an email form.

[vysor-non-support.mov.zip](https://github.com/koush/vysor.io/files/4665196/vysor-non-support.mov.zip)

**Comment by koush** [comment]
Yeah, to be honest, I prefer not to put this issue tracker on the site, because it gets absolutely flooded with low quality bug reports by people who did not bother to go through the menu and just want personal assistance. The primary problems people encounter are related to device connectivity or licensing. The site is meant to catch those. And that covers like 95% of the problems.

Technically savvy people people find the the actual bug tracker (like you did), and provide high quality bugs: the template is properly filled out, it has an attached bug report, screenshots. Or in your case, you provided a movie.
