### ISSUE TITLE
Unable to record video after latest update

### ISSUE THREAD

**Issue by ecramer** [koush/vysor.io#609]
**Describe the bug**
Recording does not work after upgrade to 3.1.4

**To Reproduce**
1. Click on record button, recording starts
2. Click record button again, recording stops

**Expected behavior**
A dialog appears asking me where I want to save my video. It does not do this. The video is not saved anywhere.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Vysor Version 3.1.4

**Android (please complete the following information):**
 - Device: Pixel 2
 - OS: Android 10
 - Vysor Bug Report Link: https://gist.github.com/VysorLogs/e0223238ac5a6614cfab565ab8be4e84

**Comment by koush** [comment]
Thanks, the error looks familiar. That's what happens when there is a single frame with no changes to the screen:

> java.lang.IllegalStateException: Failed to stop the muxer

This can be reproduced by clicking start and stop recording quickly. Can you try the followng:

1. Start recording
2. Navigate to a couple different apps
3. Stop recording

See if that works.

**Comment by ecramer** [comment]
Understood. Yes it does. Thanks!
