### ISSUE TITLE
WebAssembly decoder is the only one working reliably

### ISSUE THREAD

**Issue by Heretushi** [koush/vysor.io#654]
**Describe the bug**
When selecting any video decoder other than the default WebAssembly, the decoder do not work. 

**Attach a Vysor Bug Report Log**
https://gist.github.com/2d4d2b627cc5b7d3bd9a94dbc30c1389

**To Reproduce**
1. View selected phone in Vysor.
2. Access the settings.
3. Change the video decoder setting :

If selecting either "Native Software (Fast)", "Native Hardware (fastest)" or "Native hardware with fallback" =
4. Vysor will stay at "Waiting for decoder" and eventually complain that the phone is no longer connected.

If selecting "WebCodec (experimental)" =
4. Vysor will display green flashes erratically instead of the normal video stream.

**Expected behavior**
I expect video to work.

**Screenshots**
Here is a video : https://imgur.com/a/iAfO8Bg

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Vysor Version : 3.2.29

**Android (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 11
 - Vysor Bug Report Link: https://gist.github.com/2d4d2b627cc5b7d3bd9a94dbc30c1389

**Android Logcat**
Not familiar, please instruct.

**Additional context**
None.

**Comment by koush** [comment]
oh, you're using the progressive web app? Yes, I can confirm the webassembly decoder is the only one that will work. Chrome removed support for PNaCL fairly recently, which killed the "Native" decoder support.

I would download the desktop apps for the native decoder support. WebCodec will also be available soon, but it's still too flaky at the moment (due to it being a chrome beta feature).
