### ISSUE TITLE
[ENHANCEMENT] Anonymized Bug Reports 

### ISSUE THREAD

**Issue by dieskim** [koush/vysor.io#806]
**Describe the bug**
When submitting a bug report it contains personal information. Email, Personal Paths with usernames etc

This might prevent people from being comfortable with attaching their bug report gist to an issue as they might not want their email and other details out in the wild?

Maybe its just me but this seems like a good enhancement for privacy?

Thanks

**Comment by CCattano** [comment]
I've also noticed this and definitely agree.

@koush when we make a bug report it seems to be filed in some kind of a private repo we cannot access

![image](https://user-images.githubusercontent.com/47487276/121713937-ffcbef80-caa2-11eb-879d-465e83bc49ff.png)

If you have a direct access link it seems anyone can access the file in the repo that is linked to, but cannot navigate/search/explore the repo itself.

In the screenshot I linked the guid in the name of the text file is different from the guid in URI to access the file.

Would it be sufficient if we provided you the name of the file and you could search it yourself in the private VysorLog repo that we cannot access?

That way we don't have to publicly provide a link to it that anyone can access?

**Comment by koush** [comment]
> If you have a direct access link it seems anyone can access the file in the repo

Currently the bug reports themselves are private, the link itself can not be "guessed" by the public as it is a random UUID.
The issue here is that my current bug report template tells people to share the link, and that is what ends up exposing it to the public.

There are two fixes here:
 * make the personally identifiable information opt in on the logs-- unfortunately I still need this if I'm handling licensing issues.
 * make the users share a searchable token that only I can find, as shown above

I'm leaning towards option 1. Most of my licensing issues are handled outside of this issue tracker anyways.

**Comment by dieskim** [comment]
yeah I think option 1 sounds good

**Comment by koush** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/73924/125130061-32bece80-e0b5-11eb-8dc1-419c0d27cfb2.png">
