### ISSUE TITLE
Linux: provide AppImage

### ISSUE THREAD

**Issue by navarroaxel** [koush/vysor.io#813]
Hi, could you please provide an AppImage for the latest stable release `4.1.14`? Then I can update the AUR package for the Arch Linux distros https://aur.archlinux.org/packages/vysor-appimage

**Comment by koush** [comment]
Thanks for doing this. Forgive me since I'm not really savvy with Linux distributions. Is there any reason you can't create an AUR from the deb? I just set up a Debian repository yesterday, and was considering phasing out the other builds, since I can't reasonably test them all:

 * snap (didn't work right and was unreliable due to sandboxing issues that got worse with iOS support)
 * appimage (doesn't create a launcher icon unless appimage launcher was installed)
 * pacman

**Comment by koush** [comment]
apt repo instructions here https://www.vysor.io/download/linux

**Comment by navarroaxel** [comment]
Done: https://aur.archlinux.org/packages/vysor-bin now we use the package files from the `.deb` package

:raised_hands:

**Comment by navarroaxel** [comment]
@koush, done. :raised_hands: 

https://aur.archlinux.org/packages/vysor-bin now we use the package files from the `.deb` package
