### ISSUE TITLE
Device Screen sharing

### ISSUE THREAD

**Issue by lkaranam** [koush/vysor.io#96]
Is there a way to embed Vysor android screen into web application or JSP? I would like to show the device screen to the end user who is running that web application. If not, could you please let me know if there is a way to generate device sharing URL programatially using Vysor app?

**Comment by Naresh-Edla** [comment]
Hi lkaranam,
  I'm also looking for the same. Have you got anything on it?

**Comment by marconetwo** [comment]
Sorry, but you can't call it device "mirroring" if it DOESNT SEND THE AUDIO TOO!
Why isn't this a much bigger deal.
F going wireless if I literally have to run ANOTHER cable from my LG G4 stereo analog/microphone
in jack to the line/mic input jack on my laptop, then configure the mixer to route the mic input DAC
(actually ADC) to be mixed in with the 5.1 HD-Audio component of the HDMI feed that runs to my
1080p TV, that (luckily) has an optical audio out I plug into my Audio Processor/Amp and feed my
(emulated) 6.1 surround sound to my left and right full range speakers, the center for movie dialogue,
and the back three surround speakers (BL BC BR).

Digital Audio was much easier in the early/mid 80's, and way better sounding, when I had my
Krell KSA-250 (pure class-A -- $7,000), and the pair of B&W 801 series II matrix speakers (~ $5,000),
being either fed directly from the output the first (and awsome sounding) portable (12-13V) digital
recorder made by sony, the PCM-F1 with the brickwall filter replaced with Apogee digital
oversampling filters.  Of course it sat atop the portable Betamax recorder (b4 CD's -- remember)
because Beta is and always was better, though not at advertising -- so less chance of any
droupouts that way.  (even one is one way too many).  And a subwoffer, Ahhh, don't think so.
801's series II with optional 6th order butterworth active passover rached the low end amplitude
response flat down to 18 cps (and it's a myth you can't tell where the low end is coming from.
*I* can.

My point, besides reminicising about the recording technology (spaced omni shoeps capsules),
capturing the live sound of the greatest innovation in sound "reenforcement", bar none, by the greatest
sound researcher in existance, John Meyer, and how the Dead (the real, pre 1995 Dead) got better
sound from Johns MSL series self powered full range octaganal (sp? patent...) speaker arrays. And
how *everyone*, from the NY philharmonic, to Ringling Bros, etc... all use them, but hardly anyone knows it's only because Garcial called John in Eurpoe and said, *PLease*, you have to come home
and solve our audio woes (the wall of sound, n.b. the alembic system, cost More To Run than they
were taking in at the box office.  Well, if it wasn't for that call, we'd still have crappy PA systems.

SO again, my friggin point.
FIX THE STUPID AUDIO ROUTING TO GO TO THE Chrome Browser, or I'll bore you with more
and LONGER stories.  In that, you have my promise.  -- Marc Teitelbaum

**Comment by koush** [comment]
Today I learned mirrors reflect sound.

**Comment by koush** [comment]
@Naresh-Edla you may just be able to iframe the share url.
